### ISSUE TITLE
KeyError "config" when DockerSpawner.remove = True

### ISSUE THREAD

**Issue by cablesky** [jupyterhub/nativeauthenticator#158]
Environment: JupyterHub in Docker Swarm with NativeAuthenticator

When the Flag c.DockerSpawner.remove = True , and i Stop the Notebook from the Web-Panel, and start the Notebook again, there is the Error: "Error: HTTP 500: Internal Server Error (Error in Authenticator.pre_spawn_start: KeyError 'Config')"

**Comment by cablesky** [comment]
Yes, of course...
Thank you for your help!

`[D 2021-10-21 12:06:44.528 JupyterHub dockerspawner:557] Getting container 'jupyter-abc',
[D 2021-10-21 12:06:44.540 JupyterHub swarmspawner:125] Service q93137b status: {'ContainerStatus': {'ContainerID': '111fca81ba1cd30f212e94ed338d5bedd3d1dccfdd20736f391c8765d48e9640',,
                         'ExitCode': 0,,
                         'PID': 2228027},,
     'Message': 'started',,
     'PortStatus': {},,
     'State': 'running',,
     'Timestamp': '2021-10-21T12:06:12.994329879Z'},
[I 2021-10-21 12:06:44.540 JupyterHub dockerspawner:793] Stopping service jupyter-abc (id: q93137b),
[D 2021-10-21 12:06:44.570 JupyterHub user:848] Finished stopping abc,
[E 2021-10-21 12:06:44.600 JupyterHub pages:261] Failed to spawn single-user server with form,
    Traceback (most recent call last):,
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/pages.py", line 257, in post,
        return await self._wrap_spawn_single_user(,
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/pages.py", line 314, in _wrap_spawn_single_user,
        raise web.HTTPError(,
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Error in Authenticator.pre_spawn_start: KeyError 'Config'),`
