### ISSUE TITLE
Some questions in normal installation

### ISSUE THREAD

**Issue by 00Kai0** [jupyterhub/nativeauthenticator#45]
@leportella
When I install this module (not develop install), I find some questions.
1.
After `pip install .`, I use `from nativeauthenticator import NativeAuthenticator`.It shows some error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kai/work/embark3_env/venv/lib/python3.5/site-packages/nativeauthenticator/__init__.py", line 4, in <module>
    from nativeauthenticator.nativeauthenticator import NativeAuthenticator
  File "/home/kai/work/embark3_env/venv/lib/python3.5/site-packages/nativeauthenticator/nativeauthenticator.py", line 1, in <module>
    import bcrypt
ImportError: No module named 'bcrypt'
```
I saw you put `bcrypt` into `dev-requirements.txt`, I think you should put it into `setup.py`'s `install_requires`. (It just my suggestions).
2.
It's about `f-string`.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kai/work/embark3_env/venv/lib/python3.5/site-packages/nativeauthenticator/__init__.py", line 4, in <module>
    from nativeauthenticator.nativeauthenticator import NativeAuthenticator
  File "/home/kai/work/embark3_env/venv/lib/python3.5/site-packages/nativeauthenticator/nativeauthenticator.py", line 10, in <module>
    from .handlers import (AuthorizationHandler, ChangeAuthorizationHandler,
  File "/home/kai/work/embark3_env/venv/lib/python3.5/site-packages/nativeauthenticator/handlers.py", line 53
    f"at least {pw_len} characters, doesn't have "
    ^
SyntaxError: invalid syntax
```
This is a new string format in `python3.6` (I usually use `python3.5`). If you just want to support `python>=3.6`, you need set `python_requires=">=3.6"` in `setup.py`. The other way is changing the format style to support `3.4` or `3.5`.
This is all my questions. Thank you.
If you wanne help, I can have a try.

**Comment by leportella** [comment]
@00Kai0 thanks for your feedback! I'll remove the f-string to assure backward compability and will add bcrypt as a dependency as well!
