### ISSUE TITLE
Error on user deletion

### ISSUE THREAD

**Issue by chicocvenancio** [jupyterhub/nativeauthenticator#92]
As a workaround to #90 I hit this exception:
```
[E 2020-01-13 19:51:34.834 JupyterHub web:1788] Uncaught exception DELETE /hub/api/users/SOMEUSER (*.*.*.*)
    HTTPServerRequest(protocol='https', host='', method='DELETE', uri='/hub/api/users/SOMEUSER', version='HTTP/1.1', remote_ip='10.0.45.103')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/apihandlers/users.py", line 184, in delete
        await maybe_future(self.authenticator.delete_user(user))
      File "/home/jovyan/.local/lib/python3.6/site-packages/nativeauthenticator/nativeauthenticator.py", line 217, in delete_user
        self.db.delete(user_info)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1992, in delete
        raise exc.UnmappedInstanceError(instance)
    sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped
```

**Comment by lambdaTotoro** [comment]
There already is an unmerged pull request from last August (#80) that addresses this.

**Comment by leportella** [comment]
fixed
